name: CI
on: [push, pull_request]
env:
  TZ: /usr/share/zoneinfo/Asia/Tokyo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.7
    - name: run tests
      run: ./tutorial/retrospectives/test.sh
